export const balanceData = [
  {
    id: 1,
    title: "Add New",
    balance: 420.69,
    emojiIcon: "",
    percentRemaining: 0.69,
  },
  {
    id: 2,
    title: "Groceries",
    balance: 150,
    emojiIcon: "🍎",
    percentRemaining: 0.5,
  },
  {
    id: 3,
    title: "Gift Fund",
    balance: 500,
    emojiIcon: "🎉",
    percentRemaining: 0.8,
  },
  {
    id: 4,
    title: "Dining Out",
    balance: 49,
    emojiIcon: "🍗",
    percentRemaining: 0.23,
  },
  {
    id: 5,
    title: "Gasoline",
    balance: 55,
    emojiIcon: "⛽️",
    percentRemaining: 0.45,
  },
  {
    id: 6,
    title: "Golf",
    balance: 90,
    emojiIcon: "⛳️",
    percentRemaining: 0.73,
  },
  {
    id: 7,
    title: "Subscriptions",
    balance: 5,
    emojiIcon: "💸",
    percentRemaining: 0.05,
  },
  {
    id: 8,
    title: "Amazon",
    balance: 20,
    emojiIcon: "📦",
    percentRemaining: 1,
  },
  {
    id: 9,
    title: "Fitness",
    balance: 18,
    emojiIcon: "💪",
    percentRemaining: 0.23,
  },
  {
    id: 10,
    title: "Video Games",
    balance: 15,
    emojiIcon: "👾",
    percentRemaining: 0.9,
  },
  // {
  //   id: 11,
  //   title: "Donations",
  //   balance: 140,
  //   emojiIcon: "⛪️",
  //   percentRemaining: 0.96,
  // },
  // {
  //   id: 12,
  //   title: "Catch-All",
  //   balance: 140,
  //   emojiIcon: "🛟",
  //   percentRemaining: 0.8,
  // },
];
