export const budgetData = [
  {
    id: 1,
    title: "Add New",
    balance: 420.69,
    emojiIcon: "",
    percentRemaining: 0.69,
    balanceType: "BUDGET",
  },
  {
    id: 2,
    title: "Groceries",
    balance: 150,
    emojiIcon: "🍎",
    percentRemaining: 0.5,
    balanceType: "BUDGET",
  },
  {
    id: 3,
    title: "Gift Fund",
    balance: 500,
    emojiIcon: "🎉",
    percentRemaining: 0.8,
    balanceType: "BUDGET",
  },
  {
    id: 4,
    title: "Dining Out",
    balance: 49,
    emojiIcon: "🍗",
    percentRemaining: 0.23,
    balanceType: "BUDGET",
  },
  {
    id: 5,
    title: "Gasoline",
    balance: 55,
    emojiIcon: "⛽️",
    percentRemaining: 0.45,
    balanceType: "BUDGET",
  },
  {
    id: 6,
    title: "Golf",
    balance: 90,
    emojiIcon: "⛳️",
    percentRemaining: 0.73,
    balanceType: "BUDGET",
  },
  {
    id: 7,
    title: "Subscriptions",
    balance: 5,
    emojiIcon: "💸",
    percentRemaining: 0.05,
    balanceType: "BUDGET",
  },
  {
    id: 8,
    title: "Amazon",
    balance: 20,
    emojiIcon: "📦",
    percentRemaining: 1,
    balanceType: "BUDGET",
  },
  {
    id: 9,
    title: "Fitness",
    balance: 18,
    emojiIcon: "💪",
    percentRemaining: 0.23,
    balanceType: "BUDGET",
  },
  {
    id: 10,
    title: "Video Games",
    balance: 15,
    emojiIcon: "👾",
    percentRemaining: 0.9,
    balanceType: "BUDGET",
  },
  {
    id: 11,
    title: "Donations",
    balance: 140,
    emojiIcon: "⛪️",
    percentRemaining: 0.96,
    balanceType: "BUDGET",
  },
  {
    id: 12,
    title: "Catch-All",
    balance: 140,
    emojiIcon: "🛟",
    percentRemaining: 0.8,
    balanceType: "BUDGET",
  },
  {
    id: 13,
    title: "Dookie",
    balance: 140,
    emojiIcon: "🛟",
    percentRemaining: 0.8,
    balanceType: "BUDGET",
  },
  {
    id: 14,
    title: "Dookie",
    balance: 140,
    emojiIcon: "🛟",
    percentRemaining: 0.8,
    balanceType: "BUDGET",
  },
  {
    id: 15,
    title: "Dookie",
    balance: 140,
    emojiIcon: "🛟",
    percentRemaining: 0.8,
    balanceType: "BUDGET",
  },
  {
    id: 16,
    title: "Dookie",
    balance: 140,
    emojiIcon: "🛟",
    percentRemaining: 0.8,
    balanceType: "BUDGET",
  },
];

export const goalData = [
  {
    id: 1,
    title: "Add New",
    balance: 420.69,
    emojiIcon: "",
    percentRemaining: 0.69,
    balanceType: "GOAL",
  },
  {
    id: 2,
    title: "Wedding",
    balance: 6000,
    emojiIcon: "💎",
    percentRemaining: 0.5,
    balanceType: "GOAL",
  },
  {
    id: 3,
    title: "Emergency",
    balance: 20000,
    emojiIcon: "☔️",
    percentRemaining: 0.8,
    balanceType: "GOAL",
  },
  {
    id: 4,
    title: "Infiniti G35",
    balance: 3000,
    emojiIcon: "🚘",
    percentRemaining: 0.75,
    balanceType: "GOAL",
  },
  {
    id: 5,
    title: "College",
    balance: 5535,
    emojiIcon: "🎓",
    percentRemaining: 0.26,
    balanceType: "GOAL",
  },
  {
    id: 6,
    title: "Golf",
    balance: 90,
    emojiIcon: "⛳️",
    percentRemaining: 0.73,
    balanceType: "GOAL",
  },
  {
    id: 7,
    title: "Subscriptions",
    balance: 5,
    emojiIcon: "💸",
    percentRemaining: 0.05,
    balanceType: "GOAL",
  },
  {
    id: 8,
    title: "Amazon",
    balance: 20,
    emojiIcon: "📦",
    percentRemaining: 1,
    balanceType: "GOAL",
  },
  {
    id: 9,
    title: "Fitness",
    balance: 18,
    emojiIcon: "💪",
    percentRemaining: 0.23,
    balanceType: "GOAL",
  },
  {
    id: 10,
    title: "Video Games",
    balance: 15,
    emojiIcon: "👾",
    percentRemaining: 0.9,
    balanceType: "GOAL",
  },
  {
    id: 11,
    title: "Donations",
    balance: 140,
    emojiIcon: "⛪️",
    percentRemaining: 0.96,
    balanceType: "GOAL",
  },
  {
    id: 12,
    title: "Catch-All",
    balance: 140,
    emojiIcon: "🛟",
    percentRemaining: 0.8,
    balanceType: "GOAL",
  },
];
