import { FundButtonProps } from "../FundButtons/types";

export const fundDataHardCoded: FundButtonProps[] = [
  {
    id: "1",
    title: "Add New",
    balance: 420.69,
    emojiIcon: "",
    percentRemaining: 0.69,
    fundType: "BUDGET",
    placementIndex: 1,
  },
  {
    id: "2",
    title: "Groceries",
    balance: 150,
    emojiIcon: "🍎",
    percentRemaining: 0.5,
    fundType: "BUDGET",
    placementIndex: 2,
  },
  {
    id: "3",
    title: "Gift Fund",
    balance: 500,
    emojiIcon: "🎉",
    percentRemaining: 0.8,
    fundType: "BUDGET",
    placementIndex: 3,
  },
  {
    id: "4",
    title: "Dining Out",
    balance: 49,
    emojiIcon: "🍗",
    percentRemaining: 0.23,
    fundType: "BUDGET",
    placementIndex: 4,
  },
  {
    id: "5",
    title: "Gasoline",
    balance: 55,
    emojiIcon: "⛽️",
    percentRemaining: 0.45,
    fundType: "BUDGET",
    placementIndex: 5,
  },
  {
    id: "6",
    title: "Golf",
    balance: 90,
    emojiIcon: "⛳️",
    percentRemaining: 0.73,
    fundType: "BUDGET",
    placementIndex: 6,
  },
  {
    id: "7",
    title: "Subscriptions",
    balance: 5,
    emojiIcon: "💸",
    percentRemaining: 0.05,
    fundType: "BUDGET",
    placementIndex: 7,
  },
  {
    id: "8",
    title: "Amazon",
    balance: 20,
    emojiIcon: "📦",
    percentRemaining: 1,
    fundType: "BUDGET",
    placementIndex: 8,
  },
  {
    id: "9",
    title: "Fitness",
    balance: 18,
    emojiIcon: "💪",
    percentRemaining: 0.23,
    fundType: "BUDGET",
    placementIndex: 9,
  },
  {
    id: "10",
    title: "Video' G'ames",
    balance: 15,
    emojiIcon: "👾",
    percentRemaining: 0.9,
    fundType: "BUDGET",
    placementIndex: 10,
  },
  {
    id: "11",
    title: "Donations",
    balance: 140,
    emojiIcon: "⛪️",
    percentRemaining: 0.96,
    fundType: "BUDGET",
    placementIndex: 11,
  },
  {
    id: "12",
    title: "Catch-All",
    balance: 140,
    emojiIcon: "🛟",
    percentRemaining: 0.8,
    fundType: "BUDGET",
    placementIndex: 12,
  },
  {
    id: "13",
    title: "Template",
    balance: 140,
    emojiIcon: "🛟",
    percentRemaining: 0.8,
    fundType: "BUDGET",
    placementIndex: 13,
  },
  {
    id: "14",
    title: "Template",
    balance: 140,
    emojiIcon: "🛟",
    percentRemaining: 0.8,
    fundType: "BUDGET",
    placementIndex: 14,
  },
  {
    id: "15",
    title: "Template",
    balance: 140,
    emojiIcon: "🛟",
    percentRemaining: 0.8,
    fundType: "BUDGET",
    placementIndex: 15,
  },
  {
    id: "16",
    title: "Template",
    balance: 140,
    emojiIcon: "🛟",
    percentRemaining: 0.8,
    fundType: "BUDGET",
    placementIndex: 16,
  },
];

export const goalData = [
  {
    id: 1,
    title: "Add New",
    balance: 420.69,
    emojiIcon: "",
    percentRemaining: 0.69,
    fundType: "GOAL",
    placement_index: 1,
  },
  {
    id: 2,
    title: "Wedding",
    balance: 6000,
    emojiIcon: "💎",
    percentRemaining: 0.5,
    fundType: "GOAL",
    placement_index: 2,
  },
  {
    id: 3,
    title: "Emergency",
    balance: 20000,
    emojiIcon: "☔️",
    percentRemaining: 0.8,
    fundType: "GOAL",
    placement_index: 3,
  },
  {
    id: 4,
    title: "Infiniti G35",
    balance: 3000,
    emojiIcon: "🚘",
    percentRemaining: 0.75,
    fundType: "GOAL",
    placement_index: 4,
  },
  {
    id: 5,
    title: "College",
    balance: 5535,
    emojiIcon: "🎓",
    percentRemaining: 0.26,
    fundType: "GOAL",
    placement_index: 5,
  },
  {
    id: 6,
    title: "Golf",
    balance: 90,
    emojiIcon: "⛳️",
    percentRemaining: 0.73,
    fundType: "GOAL",
    placement_index: 6,
  },
  {
    id: 7,
    title: "Subscriptions",
    balance: 5,
    emojiIcon: "💸",
    percentRemaining: 0.05,
    fundType: "GOAL",
    placement_index: 7,
  },
  {
    id: 8,
    title: "Amazon",
    balance: 20,
    emojiIcon: "📦",
    percentRemaining: 1,
    fundType: "GOAL",
    placement_index: 8,
  },
  {
    id: 9,
    title: "Fitness",
    balance: 18,
    emojiIcon: "💪",
    percentRemaining: 0.23,
    fundType: "GOAL",
    placement_index: 9,
  },
  {
    id: 10,
    title: "Video Games",
    balance: 15,
    emojiIcon: "👾",
    percentRemaining: 0.9,
    fundType: "GOAL",
    placement_index: 10,
  },
  {
    id: 11,
    title: "Donations",
    balance: 140,
    emojiIcon: "⛪️",
    percentRemaining: 0.96,
    fundType: "GOAL",
    placement_index: 11,
  },
  {
    id: 12,
    title: "Catch-All",
    balance: 140,
    emojiIcon: "🛟",
    percentRemaining: 0.8,
    fundType: "GOAL",
    placement_index: 12,
  },
];
